# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\mogoo\workspace\python\DebugTools\tools\..\checkBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_checkBox(object):
    def setupUi(self, checkBox):
        checkBox.setObjectName("checkBox")
        checkBox.resize(1000, 600)
        checkBox.setMinimumSize(QtCore.QSize(1000, 600))
        checkBox.setTitle("")
        self.gridLayout_2 = QtWidgets.QGridLayout(checkBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(checkBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(600, 45))
        self.widget.setMaximumSize(QtCore.QSize(500, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.textEdit_ipa = QtWidgets.QTextEdit(self.widget)
        self.textEdit_ipa.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEdit_ipa.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_ipa.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit_ipa.setObjectName("textEdit_ipa")
        self.horizontalLayout.addWidget(self.textEdit_ipa)
        self.verticalLayout.addWidget(self.widget)
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(checkBox)
        self.groupBox_5.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_5.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_check = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_check.setObjectName("btn_check")
        self.verticalLayout_3.addWidget(self.btn_check)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.groupBox_5, 1, 1, 1, 1)

        self.retranslateUi(checkBox)
        QtCore.QMetaObject.connectSlotsByName(checkBox)

    def retranslateUi(self, checkBox):
        _translate = QtCore.QCoreApplication.translate
        checkBox.setWindowTitle(_translate("checkBox", "GroupBox"))
        self.groupBox_4.setTitle(_translate("checkBox", "查询配置"))
        self.label.setText(_translate("checkBox", "资源名："))
        self.groupBox_5.setTitle(_translate("checkBox", "功能列表"))
        self.btn_check.setText(_translate("checkBox", "查询"))
