# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contentBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ContentBox(object):
    def setupUi(self, ContentBox):
        ContentBox.setObjectName("ContentBox")
        ContentBox.resize(1000, 600)
        ContentBox.setMinimumSize(QtCore.QSize(800, 480))

        self.retranslateUi(ContentBox)
        QtCore.QMetaObject.connectSlotsByName(ContentBox)

    def retranslateUi(self, ContentBox):
        _translate = QtCore.QCoreApplication.translate
        ContentBox.setWindowTitle(_translate("ContentBox", "GroupBox"))
