# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\mogoo\workspace\python\DebugTools\tools\..\crashDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_crashDialog(object):
    def setupUi(self, crashDialog):
        crashDialog.setObjectName("crashDialog")
        crashDialog.resize(640, 400)
        crashDialog.setMinimumSize(QtCore.QSize(640, 400))
        crashDialog.setMaximumSize(QtCore.QSize(640, 400))
        crashDialog.setAcceptDrops(False)
        self.widget = QtWidgets.QWidget(crashDialog)
        self.widget.setGeometry(QtCore.QRect(9, 9, 621, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(621, 41))
        self.widget.setMaximumSize(QtCore.QSize(621, 41))
        self.widget.setAcceptDrops(True)
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_parse = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_parse.sizePolicy().hasHeightForWidth())
        self.btn_parse.setSizePolicy(sizePolicy)
        self.btn_parse.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_parse.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_parse.setObjectName("btn_parse")
        self.verticalLayout.addWidget(self.btn_parse)
        self.wid_list = QtWidgets.QWidget(crashDialog)
        self.wid_list.setGeometry(QtCore.QRect(9, 59, 621, 331))
        self.wid_list.setMinimumSize(QtCore.QSize(621, 331))
        self.wid_list.setMaximumSize(QtCore.QSize(621, 331))
        self.wid_list.setObjectName("wid_list")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.wid_list)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widListLayout = QtWidgets.QHBoxLayout()
        self.widListLayout.setObjectName("widListLayout")
        self.horizontalLayout_2.addLayout(self.widListLayout)

        self.retranslateUi(crashDialog)
        QtCore.QMetaObject.connectSlotsByName(crashDialog)

    def retranslateUi(self, crashDialog):
        _translate = QtCore.QCoreApplication.translate
        crashDialog.setWindowTitle(_translate("crashDialog", "iOS崩溃解析"))
        self.btn_parse.setText(_translate("crashDialog", "解析"))
