# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crashBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_crashBox(object):
    def setupUi(self, crashBox):
        crashBox.setObjectName("crashBox")
        crashBox.resize(1000, 600)
        crashBox.setMinimumSize(QtCore.QSize(1000, 600))
        crashBox.setTitle("")
        self.gridLayout_2 = QtWidgets.QGridLayout(crashBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(crashBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(crashBox)
        self.groupBox_5.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_5.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_ipa = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_ipa.setObjectName("btn_ipa")
        self.verticalLayout_3.addWidget(self.btn_ipa)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.groupBox_5, 1, 1, 1, 1)

        self.retranslateUi(crashBox)
        QtCore.QMetaObject.connectSlotsByName(crashBox)

    def retranslateUi(self, crashBox):
        _translate = QtCore.QCoreApplication.translate
        crashBox.setWindowTitle(_translate("crashBox", "GroupBox"))
        self.groupBox_4.setTitle(_translate("crashBox", "ips配置"))
        self.groupBox_5.setTitle(_translate("crashBox", "功能列表"))
        self.btn_ipa.setText(_translate("crashBox", "开始解析"))
