# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'debugBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_debugBox(object):
    def setupUi(self, debugBox):
        debugBox.setObjectName("debugBox")
        debugBox.resize(1000, 600)
        debugBox.setMinimumSize(QtCore.QSize(1000, 600))
        self.horizontalWidget = QtWidgets.QWidget(debugBox)
        self.horizontalWidget.setGeometry(QtCore.QRect(30, 40, 351, 80))
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.no = QtWidgets.QRadioButton(self.horizontalWidget)
        self.no.setObjectName("no")
        self.horizontalLayout.addWidget(self.no)
        self.yes = QtWidgets.QRadioButton(self.horizontalWidget)
        self.yes.setObjectName("yes")
        self.horizontalLayout.addWidget(self.yes)

        self.retranslateUi(debugBox)
        QtCore.QMetaObject.connectSlotsByName(debugBox)

    def retranslateUi(self, debugBox):
        _translate = QtCore.QCoreApplication.translate
        debugBox.setWindowTitle(_translate("debugBox", "GroupBox"))
        debugBox.setTitle(_translate("debugBox", "调试配置"))
        self.label.setText(_translate("debugBox", "模拟pad"))
        self.no.setText(_translate("debugBox", "否"))
        self.yes.setText(_translate("debugBox", "是"))
