# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\mogoo\workspace\Python\DebugTools\tools\..\hotupdateBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_hotupdateBox(object):
    def setupUi(self, hotupdateBox):
        hotupdateBox.setObjectName("hotupdateBox")
        hotupdateBox.resize(1000, 600)
        hotupdateBox.setMinimumSize(QtCore.QSize(1000, 600))
        self.widget_2 = QtWidgets.QWidget(hotupdateBox)
        self.widget_2.setGeometry(QtCore.QRect(30, 110, 541, 41))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.widget_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)

        self.retranslateUi(hotupdateBox)
        QtCore.QMetaObject.connectSlotsByName(hotupdateBox)

    def retranslateUi(self, hotupdateBox):
        _translate = QtCore.QCoreApplication.translate
        hotupdateBox.setWindowTitle(_translate("hotupdateBox", "GroupBox"))
        hotupdateBox.setTitle(_translate("hotupdateBox", "上传热更新"))
