# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/jinshan/workspace/win/DebugTools/tools/../packageBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_packageBox(object):
    def setupUi(self, packageBox):
        packageBox.setObjectName("packageBox")
        packageBox.resize(1000, 600)
        packageBox.setMinimumSize(QtCore.QSize(1000, 600))

        self.retranslateUi(packageBox)
        QtCore.QMetaObject.connectSlotsByName(packageBox)

    def retranslateUi(self, packageBox):
        _translate = QtCore.QCoreApplication.translate
        packageBox.setWindowTitle(_translate("packageBox", "TabWidget"))
