# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'packageCheckBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_packageCheckBox(object):
    def setupUi(self, packageCheckBox):
        packageCheckBox.setObjectName("packageCheckBox")
        packageCheckBox.resize(1000, 600)
        packageCheckBox.setMinimumSize(QtCore.QSize(1000, 600))
        packageCheckBox.setTitle("")
        self.gridLayout_2 = QtWidgets.QGridLayout(packageCheckBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(packageCheckBox)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(packageCheckBox)
        self.groupBox_5.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_5.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_check = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_check.setObjectName("btn_check")
        self.verticalLayout_3.addWidget(self.btn_check)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.widget = QtWidgets.QWidget(packageCheckBox)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setReadOnly(True)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.textEdit)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 2)

        self.retranslateUi(packageCheckBox)
        QtCore.QMetaObject.connectSlotsByName(packageCheckBox)

    def retranslateUi(self, packageCheckBox):
        _translate = QtCore.QCoreApplication.translate
        packageCheckBox.setWindowTitle(_translate("packageCheckBox", "GroupBox"))
        self.groupBox.setTitle(_translate("packageCheckBox", "输出结果"))
        self.groupBox_5.setTitle(_translate("packageCheckBox", "功能列表"))
        self.btn_check.setText(_translate("packageCheckBox", "开始检测"))
        self.label_2.setText(_translate("packageCheckBox", "游戏包路径："))
        self.textEdit.setPlaceholderText(_translate("packageCheckBox", "点击[选择]按钮游戏包..."))
        self.pushButton.setText(_translate("packageCheckBox", "选择"))
