# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tabForm(object):
    def setupUi(self, tabForm):
        tabForm.setObjectName("tabForm")
        tabForm.resize(1280, 720)
        tabForm.setMaximumSize(QtCore.QSize(1280, 720))
        self.verticalLayout = QtWidgets.QVBoxLayout(tabForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gameView = QtWidgets.QWidget(tabForm)
        self.gameView.setMinimumSize(QtCore.QSize(0, 100))
        self.gameView.setMaximumSize(QtCore.QSize(16777215, 100))
        self.gameView.setObjectName("gameView")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.gameView)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tedProject = QtWidgets.QTextEdit(self.gameView)
        self.tedProject.setMinimumSize(QtCore.QSize(400, 50))
        self.tedProject.setMaximumSize(QtCore.QSize(400, 50))
        self.tedProject.setObjectName("tedProject")
        self.horizontalLayout_2.addWidget(self.tedProject)
        self.btnSetting = QtWidgets.QPushButton(self.gameView)
        self.btnSetting.setObjectName("btnSetting")
        self.horizontalLayout_2.addWidget(self.btnSetting)
        self.verticalLayout.addWidget(self.gameView, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.contentView = QtWidgets.QWidget(tabForm)
        self.contentView.setObjectName("contentView")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contentView)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(self.contentView)
        self.listWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.widget_2 = QtWidgets.QWidget(self.contentView)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.contentView)
        self.contentView.raise_()
        self.gameView.raise_()

        self.retranslateUi(tabForm)
        QtCore.QMetaObject.connectSlotsByName(tabForm)

    def retranslateUi(self, tabForm):
        _translate = QtCore.QCoreApplication.translate
        tabForm.setWindowTitle(_translate("tabForm", "Form"))
        self.btnSetting.setText(_translate("tabForm", "设置"))
