# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/jinshan/workspace/win/DebugTools/tools/../uploadBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_uploadBox(object):
    def setupUi(self, uploadBox):
        uploadBox.setObjectName("uploadBox")
        uploadBox.resize(1000, 600)
        uploadBox.setMinimumSize(QtCore.QSize(1000, 600))

        self.retranslateUi(uploadBox)
        QtCore.QMetaObject.connectSlotsByName(uploadBox)

    def retranslateUi(self, uploadBox):
        _translate = QtCore.QCoreApplication.translate
        uploadBox.setWindowTitle(_translate("uploadBox", "GroupBox"))
        uploadBox.setTitle(_translate("uploadBox", "上传资源"))
